---
- name: "Check if wikijs is already installed"
  ansible.builtin.stat:
    path: "{{ wikijs_install_dir }}"
  register: wikijs_installed

- name: "Install requierements"
  ansible.builtin.package:
    name: "jq"
    state: present
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success
  when:
    - wikijs_installed.stat.exists

- name: "Check installed version of wikijs"
  ansible.builtin.shell: |
    set -o pipefail
    cat {{ wikijs_install_dir }}/package.json | jq -r '.version'
  args:
    executable: /bin/bash
  register: wikijs_version_installed
  changed_when: false
  when:
    - wikijs_installed.stat.exists

- name: "Install tasks"
  when: not wikijs_installed.stat.exists or wikijs_version != wikijs_version_installed.stdout_lines[0]
  block:
    - name: "Create wikijs system group"
      ansible.builtin.group:
        name: wikijs
        system: true
        state: present

    - name: "Create wikijs system user"
      ansible.builtin.user:
        name: wikijs
        system: true
        shell: "/usr/sbin/nologin"
        group: wikijs
        createhome: false
        home: "{{ wikijs_install_dir }}"

    - name: "Create install directory {{ wikijs_install_dir }}"
      ansible.builtin.file:
        path: "{{ wikijs_install_dir }}"
        state: directory
        mode: '0755'
        owner: wikijs
        group: wikijs

    - name: "Download and extract wikijs"
      ansible.builtin.unarchive:
        src: "{{ wikijs_download_url }}"
        dest: "{{ wikijs_install_dir }}/"
        remote_src: true
        mode: '0644'
        owner: wikijs
        group: wikijs
      notify: Restart wikijs

    - name: "Install sideload locales from git"
      ansible.builtin.git:
        repo: "https://github.com/Requarks/wiki-localization.git"
        dest: "{{ wikijs_install_dir }}/data/sideload"
        depth: 1    # Shallow clone
        recursive: true
        force: true
      notify: Restart wikijs

    - name: "Change ownership of sideload"
      ansible.builtin.file:
        path: "{{ wikijs_install_dir }}/data/sideload"
        owner: wikijs
        group: wikijs

- name: "Deploy config.yml"
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ wikijs_install_dir }}/config.yml"
    owner: wikijs
    group: wikijs
    mode: '0640'
  notify: Restart wikijs

- name: "Copy service file"
  ansible.builtin.template:
    src: wikijs.service.j2
    dest: "/etc/systemd/system/wikijs.service"
    owner: root
    group: root
    mode: '0640'
  notify:
    - Start wikijs
