---
- name: Start wikijs
  ansible.builtin.service:
    name: wikijs
    state: started
    enabled: true
    daemon_reload: true

- name: "Restart wikijs"
  ansible.builtin.service:
    name: wikijs
    state: restarted
